# ~/.streamlit/config.toml

[server]
# Permite que a página do Streamlit seja automaticamente atualizada quando o código-fonte for alterado
runOnSave = true

[runner]
# Permite que a aplicação continue rodando enquanto está atualizando
magicEnabled = true
liveFileWatcher = true

# Define o intervalo em que o Streamlit verifica por alterações no código-fonte
liveFileWatcherPollInterval = 0.01

[theme]
base="dark"
primaryColor="pink"     
backgroundColor = "#FFFFFF"     
secondaryBackgroundColor = "#F8F2F6"  
textColor = "#282828"           